name: Lint popup.md
on:
  push:
    branches: [main]
    paths:
      - apps/docs/packages/tma-js-sdk/features/popup.md
  pull_request:
    branches: [main]
    paths:
      - apps/docs/packages/tma-js-sdk/features/popup.md

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: apps/docs/packages/tma-js-sdk/features/popup.md
